version: "3.9"

services:
  mysql:
    image: mysql:8.0.36
    container_name: kino-mysql
    restart: unless-stopped
    volumes:
      - kino-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_SECRET_KEY} # TODO .env 설정 추가
      MYSQL_DATABASE: kino # Database 생성
      MYSQL_USER: ji
      MYSQL_PASSWORD: ${DOCKER_MYSQL_SECRET_KEY} # TODO .env 설정 추가
    ports:
      - "3306:3306"
    networks:
      - kino-net

  redis:
    image: redis:7.2.5
    container_name: kino-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - kino-net

  spring:
    image: wonny320/kino-spring:latest
    container_name: kino-spring
    restart: unless-stopped # always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://kino-mysql:3306/kino?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DOCKER_MYSQL_SECRET_KEY} # TODO .env 설정 추가
      SPRING_DATA_REDIS_HOST: kino-redis   # 컨테이너 이름과 일치하게
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    networks:
      - kino-net

volumes:
  kino-mysql:
    driver: local

networks:
  kino-net:
